(defun getVariantProperty (vla-objet property) 
  (vlax-safearray->list 
    (variant-value (vlax-get-property vla-objet property))
  )
)

(defun printSecProp (secproplist / index) 
  (setq index 0)
  (while (< index (length secproplist)) 
    (print (nth index secproplist))
    (setq index (1+ index))
  )
)

(defun c:QSEC (/ sec area perimeter cx cy ix Iy Ixy Iu Iv r ry secprop) 
  (setq sec (ssname (ssget w) 0))
  (setq sec (vlax-ename->vla-object sec))
  (setq area (vlax-get-property sec 'Area))
  (setq perimeter (vlax-get-property sec 'Perimeter))
  (setq cx (car (getVariantProperty sec 'Centroid)))
  (setq cy (nth 1 (getVariantProperty sec 'Centroid)))
  (command "ucs" (list cx cy) "")
  (setq Ix (car (getVariantProperty sec 'MomentOfInertia)))
  (setq Iy (nth 1 (getVariantProperty sec 'MomentOfInertia)))
  (setq Ixy (vlax-get-property sec 'ProductOfInertia))
  (setq Iu (car (getVariantProperty sec 'PrincipalMoments)))
  (setq Iv (nth 1 (getVariantProperty sec 'PrincipalMoments)))
  (setq rx (car (getVariantProperty sec 'RadiiOfGyration)))
  (setq ry (nth 1 (getVariantProperty sec 'RadiiOfGyration)))
  (setq secprop (list 
                  (cons 'A area)
                  (cons 'P perimeter)
                  (cons 'CX cx)
                  (cons 'CY cy)
                  (cons 'IX Ix)
                  (cons 'IY Iy)
                  (cons 'IXY Ixy)
                  (cons 'RX rx)
                  (cons 'RY ry)
                  (cons 'IU Iu)
                  (cons 'IV Iv)
                )
  )
  (command "ucs" "w" "")
  (printSecProp secprop)
) ;defun
(princ)